- ros_topic_name: "/clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

#gz topic published by Sensors plugin
- ros_topic_name: "/robot/top_laser/point_cloud"
  gz_topic_name: "/robot/top_lidar/scan/points"
  ros_type_name: "sensor_msgs/msg/PointCloud2"
  gz_type_name: "gz.msgs.PointCloudPacked"
  direction: GZ_TO_ROS


# gz topic published by Sensors plugin (Camera)
- ros_topic_name: "/robot/front_rgbd_camera/color/camera_info"
  gz_topic_name: "/robot/front_camera_color/color/camera_info"
  ros_type_name: "sensor_msgs/msg/CameraInfo"
  gz_type_name: "gz.msgs.CameraInfo"
  direction: GZ_TO_ROS

- ros_topic_name: "/robot/front_rgbd_camera/color/image_raw"
  gz_topic_name: "/robot/front_camera_color/color/image_raw"
  ros_type_name: "sensor_msgs/msg/Image"
  gz_type_name: "gz.msgs.Image"
  direction: GZ_TO_ROS


# gz topic published by Sensors plugin (IMU)
- ros_topic_name: "/robot/imu/data"
  gz_topic_name: "/robot/imu/data"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "ignition.msgs.IMU"
  direction: GZ_TO_ROS

#
# gz topic published by JointState plugin
- ros_topic_name: "/robot/joint_states"
  gz_topic_name: "joint_states"
  ros_type_name: "sensor_msgs/msg/JointState"
  gz_type_name: "gz.msgs.Model"
  direction: GZ_TO_ROS