/**:
  controller_manager:
    ros__parameters:
      use_sim_time: true
      update_rate: 100  # Hz

      joint_state_broadcaster:
        type: joint_state_broadcaster/JointStateBroadcaster

      robotnik_base_controller:
        type: robotnik_controllers/RBSummitController

  joint_state_broadcaster:
    ros__parameters:
      use_sim_time: true
      publish_rate: 200

  robotnik_base_controller:
    ros__parameters:
      use_sim_time: true
      publish_rate: 200

      #General Params
      profile: base
      debug: true
      open_loop: true

      #Timeouts
      joint_command_timeout: 0.1
      cmd_vel_timeout: 1.0

      #Odom
      odom_frame_id: robot_odom
      base_frame_id: robot_base_footprint
      use_2D_odom: true

      #Kinematics Params
      wheel_radius: 0.1125
      track_width:  0.47
      wheel_base: 0.458

      #Cartesian and wheels limits
      base:
        linear:
          x:
            velocity:
              min: -1.0
              max:  1.0
            acceleration:
              min: -1.0
              max:  1.0
          y:
            velocity:
              min: -1.0
              max:  1.0
            acceleration:
              min: -1.0
              max:  1.0
        angular:
          z:
            velocity:
              min: -1.0
              max:  1.0
            acceleration:
              min: -1.0
              max:  1.0

        front_right:
          traction:
            joint_name: robot_front_right_wheel_joint
            limits:
              velocity:
                min: -27.7
                max:  27.7
              acceleration:
                min: -10.0
                max:  10.0

        front_left:
          traction:
            joint_name: robot_front_left_wheel_joint
            limits:
              velocity:
                min: -27.7
                max:  27.7
              acceleration:
                min: -10.0
                max:  10.0

        back_right:
          traction:
            joint_name: robot_back_right_wheel_joint
            limits:
              velocity:
                min: -27.7
                max:  27.7
              acceleration:
                min: -10.0
                max:  10.0

        back_left:
          traction:
            joint_name: robot_back_left_wheel_joint
            limits:
              velocity:
                min: -27.7
                max:  27.7
              acceleration:
                min: -10.0
                max:  10.0