- ros_topic_name: "/clock"
  gz_topic_name: "clock"
  ros_type_name: "rosgraph_msgs/msg/Clock"
  gz_type_name: "gz.msgs.Clock"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin
- ros_topic_name: "/robot/front_laser/scan"
  gz_topic_name: "/robot/front_laser/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

#gz topic published by Sensors plugin
- ros_topic_name: "/robot/rear_laser/scan"
  gz_topic_name: "/robot/rear_laser/scan"
  ros_type_name: "sensor_msgs/msg/LaserScan"
  gz_type_name: "gz.msgs.LaserScan"
  direction: GZ_TO_ROS

# gz topic published by Sensors plugin (IMU)
- ros_topic_name: "/robot/imu/data"
  gz_topic_name: "/robot/imu/data"
  ros_type_name: "sensor_msgs/msg/Imu"
  gz_type_name: "ignition.msgs.IMU"
  direction: GZ_TO_ROS
